name: Test and upload .jar-file

on: push

jobs: 
 testingUploading: 
  runs-on: ubuntu-latest
  name: Testing and uploading job
  steps: 
   - uses: actions/checkout@v2
   - uses: actions/setup-java@v1
